from .load_sam3d_model import (
    NODE_CLASS_MAPPINGS as _LOAD_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _LOAD_NAMES,
)
from .sam3d_gaussian_splatting import (
    NODE_CLASS_MAPPINGS as _GS_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _GS_NAMES,
)

NODE_CLASS_MAPPINGS = {**_LOAD_CLASS, **_GS_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**_LOAD_NAMES, **_GS_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
