"""Generate the right comfy-env.toml for the host platform.

Branches on:
- Windows x64        → Python 3.12, CUDA torch from comfy-env's cu12x index
- Linux x64          → Python 3.12, CUDA torch from comfy-env's cu12x index
- DGX Spark / Linux aarch64 (Grace + Blackwell GB10) → Python 3.12 with the
  aarch64 torch index that comfy-env picks automatically.

The generated file is placed at nodes/sam3d/comfy-env.toml so comfy-env
treats it as an *isolation* env (subprocess execution) — keeping the
host ComfyUI venv untouched. install.py and prestartup_script.py both
call ensure_sam3d_toml() so the file is always in sync with the host."""

from __future__ import annotations

import logging
import platform
import sys
from pathlib import Path
from typing import Dict

log = logging.getLogger("sam3drender")

# Pin used by sam-3d-objects' inference requirements — keeping the same
# revision means depth output matches the reference pipeline exactly.
MOGE_GIT_REV = "a8c37341bc0325ca99b9d57981cc3bb2bd3e255b"
UTILS3D_GIT_REV = "3913c65d81e05e47b9f367250cf8c0f7462a0900"

SAM3D_TOML_RELPATH = Path("nodes") / "sam3d" / "comfy-env.toml"


def _is_dgx_spark() -> bool:
    """Heuristic: DGX Spark is Linux aarch64 with an NVIDIA Grace/Blackwell
    chip. We treat any Linux aarch64 box as Spark-class for env purposes —
    the only practical difference is the wheel index, which comfy-env
    resolves automatically."""
    return sys.platform.startswith("linux") and platform.machine().lower() in ("aarch64", "arm64")


def detect_target() -> Dict[str, str]:
    """Return {target, python} for the host."""
    if sys.platform == "win32":
        return {"target": "win-x64", "python": "3.12"}
    if sys.platform.startswith("linux"):
        if _is_dgx_spark():
            # DGX Spark ships with CUDA 13 + Python 3.12 by default; pin the
            # same here so pixi grabs the matching aarch64 wheels.
            return {"target": "dgx-spark", "python": "3.12"}
        return {"target": "linux-x64", "python": "3.12"}
    # Fallback for unsupported platforms (macOS, BSD, etc.) — best-effort.
    return {"target": sys.platform, "python": "3.12"}


def render_toml() -> str:
    """Build the comfy-env.toml content for the detected host."""
    info = detect_target()
    python = info["python"]
    target = info["target"]

    lines = [
        f"# Auto-generated by ComfyUI-SAM3DRender for target: {target}",
        f'python = "{python}"',
        "",
        "[cuda]",
        'packages = ["torch", "torchvision"]',
        "",
        "[pypi-dependencies]",
        f'MoGe = {{ git = "https://github.com/microsoft/MoGe.git", rev = "{MOGE_GIT_REV}" }}',
        'huggingface-hub = "*"',
        'safetensors = "*"',
        'timm = ">=0.9.16"',
        f'utils3d = {{ git = "https://github.com/EasternJournalist/utils3d.git", rev = "{UTILS3D_GIT_REV}" }}',
        'opencv-python-headless = ">=4.9.0"',
        'scipy = ">=1.11.0"',
        'numpy = ">=1.24.0,<2.0"',
        'Pillow = ">=10.0.0"',
        # ComfyUI-side imports our nodes pull in via `import comfy.utils`
        # and `import comfy.model_management`. These aren't auto-installed
        # by MoGe/timm, so list them explicitly.
        'psutil = "*"',           # comfy.model_management hard-requires
        'einops = "*"',           # comfy.utils hard-requires
        'tqdm = "*"',             # comfy.utils (tqdm.auto)
        'comfy-aimdo = "*"',      # comfy.windows -> comfy_aimdo.control (hard)
        'comfy-kitchen = "*"',    # comfy.model_management soft-imports for fp8/fp4
        "",
    ]

    if target == "dgx-spark":
        lines.append("# DGX Spark / Linux aarch64: rely on conda-forge for native libs.")
        lines.append("")

    return "\n".join(lines)


def ensure_sam3d_toml(node_dir: Path) -> Path:
    """Write nodes/sam3d/comfy-env.toml if missing or stale."""
    toml_path = node_dir / SAM3D_TOML_RELPATH
    toml_path.parent.mkdir(parents=True, exist_ok=True)
    desired = render_toml()
    if toml_path.exists() and toml_path.read_text(encoding="utf-8") == desired:
        return toml_path
    toml_path.write_text(desired, encoding="utf-8")
    log.info("[SAM3DRender] wrote %s for target=%s", toml_path, detect_target()["target"])
    return toml_path
