from .render_node import (
    NODE_CLASS_MAPPINGS as _CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _NAMES,
)
from .render_node_sam3d import (
    NODE_CLASS_MAPPINGS as _SAM3D_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _SAM3D_NAMES,
)

NODE_CLASS_MAPPINGS = {**_CLASS, **_SAM3D_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**_NAMES, **_SAM3D_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
